# Generated by droughty from the deployed warehouse. Do not edit by hand.
#
# A measure per numeric column and a count per key, as refinements onto the
# base views. Hand-written measures and anything hidden goes in the aggregate
# layer, so this file can be regenerated without losing it.

include: "/analytics_warehouse/lookml/base/_base.layer.lkml"

view: +wh_commerce__order_fact {
  measure: count_of_order_pk {
    type: count_distinct
    sql: ${order_pk} ;;
  }

  measure: sum_of_order_total_amount {
    type: sum
    sql: ${order_total_amount} ;;
  }
}

view: +wh_master__customer_dim {
  measure: count_of_customer_pk {
    type: count_distinct
    sql: ${customer_pk} ;;
  }
}

view: +wh_commerce__daily_sales_xa {
  measure: count_of_daily_sales_pk {
    type: count_distinct
    sql: ${daily_sales_pk} ;;
  }

  measure: sum_of_daily_sales_order_count {
    type: sum
    sql: ${daily_sales_order_count} ;;
  }

  measure: sum_of_daily_sales_total_amount {
    type: sum
    sql: ${daily_sales_total_amount} ;;
  }
}
