# Generated by droughty from the deployed warehouse. Do not edit by hand.
#
# One view per warehouse table, with a dimension per column. Hand-written
# labelling and grouping goes in the staging layer as a refinement, so this
# file can be regenerated without losing it.

view: wh_shop__order_fact {
  sql_table_name: wh_shop__order_fact ;;

  dimension: order_pk {
    primary_key: yes
    hidden: yes
    type: string
    sql: ${TABLE}.order_pk ;;
    description: "Surrogate key for the order."
  }

  dimension: customer_fk {
    hidden: yes
    type: string
    sql: ${TABLE}.customer_fk ;;
    description: "The customer who placed the order."
  }

  dimension: order_natural_key {
    hidden: yes
    type: string
    sql: ${TABLE}.order_natural_key ;;
    description: "The order reference from the shop platform."
  }

  dimension: order_total_amount {
    type: number
    sql: ${TABLE}.order_total_amount ;;
    description: "Order value before returns."
  }

  dimension_group: order_placed {
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.order_placed_dt ;;
    description: "Date the order was placed."
  }

  # Deliberately reads a column no model produces, so Hunter reports
  # crosslayer.field_references_missing_column. This is what a dbt column
  # rename looks like from the reporting side.
  dimension: order_channel_name {
    type: string
    sql: ${TABLE}.order_channel_name ;;
    description: "The channel the order came through."
  }
}

view: wh_shop__customer_dim {
  sql_table_name: wh_shop__customer_dim ;;

  dimension: customer_pk {
    primary_key: yes
    hidden: yes
    type: string
    sql: ${TABLE}.customer_pk ;;
    description: "Surrogate key for the customer."
  }

  dimension: customer_natural_key {
    hidden: yes
    type: string
    sql: ${TABLE}.customer_natural_key ;;
    description: "The customer reference from the shop platform."
  }

  dimension: customer_name {
    type: string
    sql: ${TABLE}.customer_name ;;
    description: "Customer name."
  }

  dimension_group: customer_joined {
    type: time
    timeframes: [raw, date, week, month, year]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.customer_joined_dt ;;
    description: "Date of the customer's first order."
  }
}

view: wh_shop__daily_sales_xa {
  sql_table_name: wh_shop__daily_sales_xa ;;

  dimension: daily_sales_pk {
    primary_key: yes
    hidden: yes
    type: string
    sql: ${TABLE}.daily_sales_pk ;;
    description: "Surrogate key for the day."
  }

  dimension: daily_sales_order_count {
    type: number
    sql: ${TABLE}.daily_sales_order_count ;;
    description: "Orders placed that day."
  }

  dimension: daily_sales_total_amount {
    type: number
    sql: ${TABLE}.daily_sales_total_amount ;;
    description: "Order value that day."
  }

  dimension_group: daily_sales {
    type: time
    timeframes: [raw, date, week, month, year]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.daily_sales_dt ;;
    description: "The day summarised."
  }
}
