#!/usr/bin/env python3
"""Generate the documentation pages that must never be hand-written.

Two of them:

* ``docs/reference/rules.md`` -- every rule, from the registry. Hand-maintaining
  a list of 77 rules guarantees it goes stale, and a stale rules reference is
  worse than none because someone will act on it.
* ``docs/example/`` -- the real output of running Hunter against
  ``examples/tiny-shop``. A screenshot would go stale the same way; this is the
  actual thing.

Run it after adding a rule or changing the example:

    python scripts/build_docs_pages.py

CI regenerates and fails if the result differs, so neither can drift.
"""

from __future__ import annotations

import datetime as dt
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

import hunter.checks  # noqa: E402, F401  registers every rule
from hunter.checks.base import REGISTRY  # noqa: E402
from hunter.emit.markdown import write_site  # noqa: E402
from hunter.emit.plain import (  # noqa: E402
    DIMENSION_EXPLANATIONS,
    DIMENSION_HEADINGS,
    severity_label,
)
from hunter.enums import Dimension  # noqa: E402
from hunter.run import run  # noqa: E402

EXAMPLE = REPO / "examples" / "tiny-shop"
DOCS = REPO / "docs"

#: Pinned so the example output never changes with the calendar.
AS_OF = dt.date(2026, 9, 8)


def rules_page() -> str:
    """Every rule, grouped by the area it scores."""
    lines = [
        "# Every rule",
        "",
        f"Hunter has {len(REGISTRY.all())} rules across "
        f"{len({rule.dimension for rule in REGISTRY.all()})} areas. This page is "
        "generated from the rules themselves, so it cannot go stale.",
        "",
        "Each rule can be switched off, reweighted or re-graded in a project's "
        "`hunter.yml`. Doing so needs a reason, and that reason is published on "
        "the conventions page of whatever the rule was run against.",
        "",
        "## What the columns mean",
        "",
        "| Column | Meaning |",
        "|---|---|",
        "| Rule | The identifier to use in `hunter.yml` and in the register |",
        "| How serious | What Hunter calls it in plain words. Only the most serious "
        "can fail a build in gate mode |",
        "| Points | What it deducts before weighting. Scaled up where more depends "
        "on the object, and scaled down for a partial gap |",
        "| Needs | The data the rule cannot run without. A rule whose data is "
        "absent is skipped, and its area says so |",
        "",
    ]

    for dimension in Dimension:
        rules = REGISTRY.by_dimension(dimension)
        heading = DIMENSION_HEADINGS[dimension]
        lines += [f"## {heading}", "", DIMENSION_EXPLANATIONS[dimension], ""]
        if not rules:
            lines += [
                "No rules yet. This area needs warehouse access, which is not read "
                "at this version, so it is excluded from the score and its weight "
                "shared across the others.",
                "",
            ]
            continue

        lines += [
            "| Rule | How serious | Points | Needs |",
            "|---|---|---|---|",
        ]
        for rule in rules:
            needs = ", ".join(rule.requires) or "nothing"
            lines.append(
                f"| `{rule.id}` | {severity_label(rule.severity)} | {rule.points:g} | {needs} |"
            )
        lines.append("")

        for rule in rules:
            lines += [
                f"### `{rule.id}`",
                "",
                f"**Reports**: {rule.title}",
                "",
                f"**Says**: {rule.consequence}",
                "",
            ]
            notes = []
            if not rule.exposure_weighted:
                notes.append(
                    "Not weighted by what depends on the object: this is about the "
                    "repository rather than one table's reach."
                )
            if rule.confidence < 1.0:
                notes.append(
                    f"Reported with a confidence of at most {rule.confidence:g}. "
                    "Below the configured floor it becomes a suggestion and is left "
                    "out of the score."
                )
            if rule.about_coverage:
                notes.append(
                    "Reports what Hunter could not check rather than what the "
                    "repository got wrong, so it never counts as a gap."
                )
            if rule.points == 0:
                notes.append("Deducts nothing. It is there to be read, not scored.")
            if notes:
                lines += ["", *[f"- {note}" for note in notes], ""]

    lines += [
        "---",
        "",
        "_Generated by `scripts/build_docs_pages.py`. Do not edit by hand._",
        "",
    ]
    return "\n".join(lines)


def example_intro(result) -> str:
    """The page that frames the generated preview."""
    score = result.score
    gaps = score.systemic_gaps
    return "\n".join(
        [
            "# See it working",
            "",
            "Everything under this section is the real output of running Hunter "
            "against [`examples/tiny-shop`](https://github.com/sav-sus/Hunter/tree/"
            "main/examples/tiny-shop), regenerated whenever the tool changes. It is "
            "not a mock-up.",
            "",
            "Two areas read as unavailable here and would not be on your "
            "repository. There is no warehouse to connect to, and git history is "
            "skipped on purpose so these pages rebuild identically from any "
            "checkout. On a real repository Hunter attributes every table to "
            "whoever wrote it.",
            "",
            "## The example project",
            "",
            "Eight tables, with one deliberate flaw per finding class. Small enough "
            "to read in a sitting, and it exercises 28 of Hunter's rules.",
            "",
            "| Table | Built to demonstrate |",
            "|---|---|",
            "| `stg_shop__orders` | Taking every column from a raw source |",
            "| `stg_shop__customers` | Nothing. The control |",
            "| `int_shop__orders` | A working step, declared temporary in the register |",
            "| `wh_shop__order_fact` | Nothing. Fully described, owned and tested |",
            "| `wh_shop__customer_dim` | No description, no owner, a key checked for "
            "uniqueness but not for being populated |",
            "| `wh_shop__daily_sales_xa` | No tests at all, and reading staging "
            "directly so skipping integration |",
            "| `wh_shop__legacy_fact` | Built with no design, read by nothing, and "
            "naming a table directly instead of through dbt |",
            "| `wh_shop__product_dim` | A dimension carrying a figure, which is how a "
            "join multiplies a total |",
            "",
            "Plus `wh_shop__forecast_fact`, which is built and switched off, and "
            "`wh_shop__supplier_dim`, which is designed and not built.",
            "",
            "## What it scores",
            "",
            f"**{score.total:g} out of 100**, grade {score.grade}. {score.interpretation}.",
            "",
            "| Area | Score | Grade |",
            "|---|---|---|",
            *[
                (
                    f"| {DIMENSION_HEADINGS[entry.dimension]} | {entry.score:g} | {entry.grade} |"
                    if entry.scored
                    else f"| {DIMENSION_HEADINGS[entry.dimension]} | not measured | - |"
                )
                for entry in score.dimensions
            ],
            "",
            f"{len(result.open_findings)} open findings, "
            f"{len(result.suggestions)} suggestion Hunter is not confident enough to "
            f"count, and {len(result.suppressed_findings)} silenced with a recorded "
            "reason.",
            "",
            (
                "No rule failed on everything it examined, so there are no systemic gaps to report."
                if not gaps
                else "Systemic gaps: "
                + ", ".join(f"{gap.rule} ({gap.failed} of {gap.checked})" for gap in gaps)
                + "."
            ),
            "",
            "## Try it yourself",
            "",
            "```bash",
            "git clone https://github.com/sav-sus/Hunter",
            "cd Hunter",
            "uv sync --all-extras",
            "",
            "uv run hunter score examples/tiny-shop",
            "uv run hunter align examples/tiny-shop",
            "uv run hunter explain wh_shop__customer_dim examples/tiny-shop",
            "uv run hunter docs build examples/tiny-shop --out /tmp/example-site",
            "```",
            "",
            "## The pages it produced",
            "",
            "| Page | What it answers |",
            "|---|---|",
            "| [Overview](index-page.md) | Is this repository in good shape, and what "
            "needs a decision |",
            "| [Designed against built](reconciliation.md) | What was asked for, what "
            "was designed, what exists |",
            "| [The business model](conceptual-model.md) | What the business needs "
            "held, and whether it is there |",
            "| [The data model](data-model.md) | The same model at three levels |",
            "| [The score](scorecard.md) | Every number and the rule behind it |",
            "| [What is built](physical-model.md) | The table catalogue |",
            "| [How it fits together](lineage.md) | Which tables feed which |",
            "| [What needs doing](debt.md) | Every open finding, grouped |",
            "| [Do the layers agree](sync.md) | Reporting layer against the data |",
            "| [The rules](conventions.md) | The ruleset it was measured against |",
            "| [What was not checked](not-checked.md) | What the score is not based on |",
            "| [Words used here](glossary.md) | Every term, defined |",
            "",
            "---",
            "",
            "_Generated by `scripts/build_docs_pages.py`. Do not edit by hand._",
            "",
        ]
    )


def build_example() -> object:
    """Render the example project's site into the documentation."""
    # read_git=False so these committed pages rebuild identically from any
    # checkout. Git dates would move them on every commit that touches the
    # example, and CI checks they have not drifted.
    result = run(EXAMPLE, as_of=AS_OF, read_git=False)

    target = DOCS / "example"
    if target.exists():
        shutil.rmtree(target)
    staging = DOCS / "_example_staging"
    if staging.exists():
        shutil.rmtree(staging)

    write_site(result, staging)
    shutil.move(str(staging / "docs"), str(target))
    shutil.rmtree(staging)

    # The example's own index becomes a page inside the docs site, so the
    # section can have a framing page of its own at index.md.
    (target / "index.md").rename(target / "index-page.md")
    (target / "index.md").write_text(example_intro(result), encoding="utf-8")

    # The example's mkdocs.yml is not wanted inside the documentation tree.
    for stray in target.glob("mkdocs.yml"):
        stray.unlink()

    return result


def write_brand_assets() -> None:
    """Copy the palette and the logo into the documentation tree.

    The stylesheet is generated from ``hunter.brand``, the same module the
    report dashboard reads, so the documentation cannot drift away from the
    product's own colours.
    """
    from hunter.brand import ASSETS
    from hunter.emit.theme import BRAND_CSS

    assets = DOCS / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    (assets / "rittman.css").write_text(BRAND_CSS, encoding="utf-8")
    for name in ("rittman-analytics.png", "favicon.ico"):
        (assets / name).write_bytes((ASSETS / name).read_bytes())
    print(f"wrote {assets.relative_to(REPO)}/ (palette and logo)")


def dashboard_page() -> str:
    """The framing page around the example's dashboard.

    The dashboard is a whole HTML document, so it cannot be embedded in a
    Markdown page without one page's stylesheet fighting the other's. It is
    served as a file and framed here instead.
    """
    return "\n".join(
        [
            "# The dashboard",
            "",
            "This is the front page of a Hunter report: the whole of "
            "[`examples/tiny-shop`](https://github.com/sav-sus/Hunter/tree/main/"
            "examples/tiny-shop) in one screen. It is generated output, not a mock-up, "
            "and it is rebuilt whenever the tool changes.",
            "",
            "[Open the dashboard](../dashboard.html){ .md-button .md-button--primary }",
            "",
            "## What is on it",
            "",
            "| Band | The question it answers |",
            "|---|---|",
            "| The number | How healthy is this repository |",
            "| Needs a decision | What has nobody decided, as opposed to not fixed |",
            "| Where the ground is being lost | Which area is costing the most points |",
            "| How much of the plan is real | How much of the business model exists |",
            "| Every entity | Where each table actually stands, in one of eleven states |",
            "| Every rule at once | Is this a few bad tables or a habit |",
            "| What everything else is built on | Which tables are load-bearing and unchecked |",
            "| Do these first | What to fix, ranked by what closing it recovers |",
            "| What this is not based on | What Hunter could not read |",
            "",
            "## How it is built",
            "",
            "One HTML file. The stylesheet, every chart and the logo are inlined, so it "
            "opens with no network and nothing beside it: from a build artifact, a "
            "shared drive or an email attachment.",
            "",
            "Every chart is SVG generated in Python rather than drawn by a charting "
            "library. That keeps the file self-contained, and it keeps the output "
            "byte-identical between runs, which is what lets the whole site be "
            "compared against a committed file in review.",
            "",
            "```bash",
            "hunter dashboard                 # one self-contained file",
            "hunter docs build                # the dashboard plus the detail pages",
            "```",
            "",
            "---",
            "",
            "_Rittman Hunter is a Rittman Analytics product._",
            "",
        ]
    )


def main() -> None:
    (DOCS / "reference").mkdir(parents=True, exist_ok=True)
    write_brand_assets()
    rules_path = DOCS / "reference" / "rules.md"
    rules_path.write_text(rules_page(), encoding="utf-8")
    print(f"wrote {rules_path.relative_to(REPO)} ({len(REGISTRY.all())} rules)")

    result = build_example()
    (DOCS / "example" / "dashboard.md").write_text(dashboard_page(), encoding="utf-8")
    pages = sorted((DOCS / "example").rglob("*.md"))
    print(f"wrote {len(pages)} example pages, score {result.score.total:g}")


if __name__ == "__main__":
    main()
